#cloud-config
package_update: true
package_upgrade: true
packages:
  - samba
  - samba-common
  - samba-dsdb-modules
  - samba-vfs-modules
  - krb5-config
  - krb5-user
  - winbind
  - libpam-winbind
  - libnss-winbind
  - dnsutils

runcmd:
  - hostnamectl set-hostname dc1.macinfra.local
  - timedatectl set-timezone Europe/Paris

  - samba-tool domain provision --use-rfc2307 --realm=MACINFRA.LOCAL --domain=MACINFRA --server-role=dc --dns-backend=SAMBA_INTERNAL --adminpass='P@ssw0rdAdmin123' --function-level=2016

  - systemctl stop systemd-resolved
  - unlink /etc/resolv.conf
  - echo "nameserver 127.0.0.1" > /etc/resolv.conf

  - systemctl enable samba-ad-dc --now

  - reboot