#cloud-config
hostname: srv-web-1
users:
  - name: deploy
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAA... # Clé SSH du développeur

packages:
  - apache2
  - php
  - php-mysql
  - unzip
  - curl
  - nodejs
  - npm
  - ufw

runcmd:
  - systemctl enable apache2
  - systemctl start apache2
  - ufw allow OpenSSH
  - ufw allow "Apache Full"
  - ufw --force enable